### ISSUE TITLE
Possibility to adjust region?

### ISSUE THREAD

**Issue by hrvylein** [rdmrocha/linkalho#13]
Is it possible to edit https://github.com/rdmrocha/linkalho/blob/d17ed70fe1a196b6534159a849959709c5e60ce2/src/generator.cpp#L17 and make adjustments to language, timezone and location to adjust the changes made to linked accounts?

Its just a minor issue, but f.e. in mk8 over LAN Play wrong nationality is displayed ingame. So i want to compile it on my own.

Thank you :)

**Comment by hrvylein** [comment]
Yeah, it works. Maybe as a feature request: Make changing region possible with a dropdown when linking accounts?

**Comment by rdmrocha** [comment]
Thanks for the suggestion. Will not implement (at least for now) due to the fact that it will introduce potential breakage in a well tested working NNID profile and that means that users might start experiencing bugs.

If you want to create a PR with the changes, I'll take a look at it and might merge it to master, but for now there's no plan to include this feature.

If you decide to go ahead, you can extract all available timezones with a **_timeLoadLocationNameList_** call but some of them might not be valid. I'd suggest filtering them and use only the ones that follow the _**Region/City**_ pattern.

Language can be extracted via **_setGetSystemLanguage_** and should be pretty simple.

Not sure if libnx provides a country code listing but if they do, I'm yet to find the correct service. In case you want to do it, the Alpha-2 country codes is pretty much a standard and should be hard to find an _include-only_ c/c++ library to provide that.

Hope it helps. Happy coding! ;)

**Comment by rdmrocha** [comment]
@hrvylein better late than never: v2.0.0 was just released with the set of feature described above
