### ISSUE TITLE
Disable cloud saves?

### ISSUE THREAD

**Issue by Chimecho** [rdmrocha/linkalho#31]
Is it possible to disable cloud saves from the profile once linked/unlinked? Or do it as part of those processes?

I have tried several times to unlink and link an account which came with cloud saves enabled from sysnand, but there is no way to deactivate them, that config persists.

This results in a cloud save check whenever you try to boot up a title, that always fails since it can't connect to ninty.

The only way this can be done right now is by booting ofw/sysnand, disable with internet connection, and then recreating the emunand from scratch.

**Comment by rdmrocha** [comment]
This is beyond the scope of this application. Unfortunately the sysmodule responsible for cloud saves is not documented and although we can try to guess how to change the setting based on the function names, it's very hard to even try to tackle it since Atmosphere does no expose that module's service in the API. 

https://switchbrew.org/wiki/OLSC_services
https://switchbrew.github.io/libnx/dir_04a7e0b94d44ce4fc7ca3462163fd33c.html

Until there's proper documentation and at least a service exposure from Atmosphere, there's not much I can even begin to do. I'd suggest you present this issue in the atmosphere github to see if SciresM is kind enough to help or even present some hints on how to achieve this.

On your side, you can always put your console in Airplane Mode and try to launch the title to see if it makes any difference.
Other than that, you can check the "_gbatemp saltynx mitm internet_" topic and see if it helps ;)

I'll be leaving this open for a couple of days until you give some feedback about the proposed workarounds and SciresM's reply in case you post the issue there.
