### ISSUE TITLE
[2.0.1] Country not changing

### ISSUE THREAD

**Issue by deejay87** [rdmrocha/linkalho#34]
Hi
I test to change the country, link unlink tested on V1 and Oled, stay everytime for "Portugal"

**Comment by rdmrocha** [comment]
Country change is a "write-only" operation when linking and isn't visible within the app since reading back current country isn't trivial and would require a reboot-after-read which isn't practical for such a small feature. It's also not visible inside the console menus as far as I know and only used by some games to show country flags.

One way you can check if the country applied is to do a manual backup, get the backup zip from the app's backup folder and after unpacking, check the `nas/[some_random_hash]_user.json` file opening it with a text file editor.

**Comment by deejay87** [comment]
Ok thanks i test this
